/**
 * Lightweight explainable risk model (weighted behavioural features).
 *
 * This is NOT a trained machine-learning model. It is a transparent scoring
 * function suitable for fleet data generated by this application. The scoring
 * logic is isolated here so it can later be replaced by a trained ML model
 * without changing feature extraction or API handlers.
 *
 * Weights (documented in server/docs/API_TASK3.md):
 * - overspeed warning alert: +12 each
 * - critical overspeed alert: +25 each
 * - restricted-zone entry: +28 each
 * - out-of-hours movement: +15 each
 * - route deviation: +12 each
 * - max speed ratio above 1.0: up to +25 ((ratio - 1) × 50, capped)
 * - average speed above 90% of limit: up to +12 ((ratio - 0.9) × 40, capped)
 */

export const RISK_WEIGHTS = {
  overspeedAlert: 12,
  criticalOverspeedAlert: 25,
  restrictedZone: 28,
  outOfHours: 15,
  routeDeviation: 12,
  maxSpeedRatioMultiplier: 50,
  maxSpeedRatioCap: 25,
  avgSpeedRatioThreshold: 0.9,
  avgSpeedRatioMultiplier: 40,
  avgSpeedRatioCap: 12,
};

export const RISK_LABEL_THRESHOLDS = {
  lowMax: 33,
  mediumMax: 66,
};

/**
 * Classify a 0–100 risk score into low / medium / high.
 * @param {number} score
 * @returns {'low'|'medium'|'high'}
 */
export function classifyRiskLabel(score) {
  const s = Math.round(Number(score));
  if (s <= RISK_LABEL_THRESHOLDS.lowMax) return 'low';
  if (s <= RISK_LABEL_THRESHOLDS.mediumMax) return 'medium';
  return 'high';
}

function pluralize(count, singular, plural = `${singular}s`) {
  return count === 1 ? `1 ${singular}` : `${count} ${plural}`;
}

/**
 * Build human-readable risk factor strings from features.
 * @param {import('./tripFeatures.js').TripFeatures & { overspeedAlertCount?: number, criticalOverspeedAlertCount?: number }} features
 * @returns {string[]}
 */
export function buildRiskFactors(features) {
  const factors = [];

  const warnAlerts = features.overspeedAlertCount ?? 0;
  const critAlerts = features.criticalOverspeedAlertCount ?? 0;

  if (critAlerts > 0) {
    factors.push(`${pluralize(critAlerts, 'critical overspeed event')}`);
  }
  if (warnAlerts > 0) {
    factors.push(`${pluralize(warnAlerts, 'overspeed event')}`);
  } else if (features.overspeedCount > 0 && critAlerts === 0) {
    factors.push(`${pluralize(features.overspeedCount, 'overspeed reading')}`);
  }

  if (features.restrictedZoneViolations > 0) {
    factors.push(
      pluralize(features.restrictedZoneViolations, 'restricted-zone entry'),
    );
  }
  if (features.outOfHoursViolations > 0) {
    factors.push(
      pluralize(features.outOfHoursViolations, 'out-of-hours violation'),
    );
  }
  if (features.routeDeviationViolations > 0) {
    factors.push(
      pluralize(features.routeDeviationViolations, 'route deviation'),
    );
  }

  if (
    features.maximumSpeedRatio != null &&
    features.maximumSpeedRatio > 1 &&
    warnAlerts === 0 &&
    critAlerts === 0
  ) {
    factors.push(
      `Peak speed reached ${(features.maximumSpeedRatio * 100).toFixed(0)}% of limit`,
    );
  }

  if (factors.length === 0) {
    factors.push('No significant behavioural violations detected');
  }

  return factors;
}

/**
 * Calculate risk score (0–100), label, and explanatory factors.
 * @param {import('./tripFeatures.js').TripFeatures & { overspeedAlertCount?: number, criticalOverspeedAlertCount?: number }} features
 * @returns {{ riskScore: number, riskLabel: 'low'|'medium'|'high', riskFactors: string[] }}
 */
export function calculateRisk(features) {
  let raw = 0;

  raw += (features.overspeedAlertCount ?? 0) * RISK_WEIGHTS.overspeedAlert;
  raw += (features.criticalOverspeedAlertCount ?? 0) * RISK_WEIGHTS.criticalOverspeedAlert;
  raw += features.restrictedZoneViolations * RISK_WEIGHTS.restrictedZone;
  raw += features.outOfHoursViolations * RISK_WEIGHTS.outOfHours;
  raw += features.routeDeviationViolations * RISK_WEIGHTS.routeDeviation;

  if (features.maximumSpeedRatio != null && features.maximumSpeedRatio > 1) {
    const bonus = Math.min(
      RISK_WEIGHTS.maxSpeedRatioCap,
      (features.maximumSpeedRatio - 1) * RISK_WEIGHTS.maxSpeedRatioMultiplier,
    );
    raw += bonus;
  }

  if (
    features.speedLimitKmh &&
    features.averageSpeedKmh != null &&
    features.averageSpeedKmh > 0
  ) {
    const avgRatio = features.averageSpeedKmh / features.speedLimitKmh;
    if (avgRatio > RISK_WEIGHTS.avgSpeedRatioThreshold) {
      const bonus = Math.min(
        RISK_WEIGHTS.avgSpeedRatioCap,
        (avgRatio - RISK_WEIGHTS.avgSpeedRatioThreshold) * RISK_WEIGHTS.avgSpeedRatioMultiplier,
      );
      raw += bonus;
    }
  }

  const riskScore = Math.min(100, Math.max(0, Math.round(raw)));
  const riskLabel = classifyRiskLabel(riskScore);
  const riskFactors = buildRiskFactors(features);

  return { riskScore, riskLabel, riskFactors };
}
